set(ITKGDCM_LOADED 1)
set(ITKGDCM_DEPENDS "ITKExpat;ITKOpenJPEG;ITKZLIB")
set(ITKGDCM_LIBRARIES "gdcmDICT;gdcmMSFF")
set(ITKGDCM_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.4")
set(ITKGDCM_LIBRARY_DIRS "")

