set(ITKGIFTI_LOADED 1)
set(ITKGIFTI_DEPENDS "ITKExpat;ITKNIFTI;ITKZLIB")
set(ITKGIFTI_LIBRARIES "ITKgiftiio")
set(ITKGIFTI_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.4")
set(ITKGIFTI_LIBRARY_DIRS "")

