set(ITKIONIFTI_LOADED 1)
set(ITKIONIFTI_DEPENDS "ITKIOImageBase;ITKNIFTI")
set(ITKIONIFTI_LIBRARIES "ITKIONIFTI")
set(ITKIONIFTI_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.4")
set(ITKIONIFTI_LIBRARY_DIRS "")

