set(ITKIOTIFF_LOADED 1)
set(ITKIOTIFF_DEPENDS "ITKIOImageBase;ITKTIFF")
set(ITKIOTIFF_LIBRARIES "ITKIOTIFF")
set(ITKIOTIFF_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.4")
set(ITKIOTIFF_LIBRARY_DIRS "")

