set(ITKIOPNG_LOADED 1)
set(ITKIOPNG_DEPENDS "ITKIOImageBase;ITKPNG")
set(ITKIOPNG_LIBRARIES "ITKIOPNG")
set(ITKIOPNG_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.4")
set(ITKIOPNG_LIBRARY_DIRS "")

