set(ITKIOGDCM_LOADED 1)
set(ITKIOGDCM_DEPENDS "ITKGDCM;ITKIOImageBase")
set(ITKIOGDCM_LIBRARIES "ITKIOGDCM")
set(ITKIOGDCM_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.4")
set(ITKIOGDCM_LIBRARY_DIRS "")

