set(ITKIOSiemens_LOADED 1)
set(ITKIOSiemens_DEPENDS "ITKIOGE;ITKIOIPL")
set(ITKIOSiemens_LIBRARIES "ITKIOSiemens")
set(ITKIOSiemens_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.4")
set(ITKIOSiemens_LIBRARY_DIRS "")

