set(ITKIONRRD_LOADED 1)
set(ITKIONRRD_DEPENDS "ITKIOImageBase;ITKNrrdIO")
set(ITKIONRRD_LIBRARIES "ITKIONRRD")
set(ITKIONRRD_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.4")
set(ITKIONRRD_LIBRARY_DIRS "")

