set(ITKIOMeta_LOADED 1)
set(ITKIOMeta_DEPENDS "ITKIOImageBase;ITKMetaIO")
set(ITKIOMeta_LIBRARIES "ITKIOMeta")
set(ITKIOMeta_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.4")
set(ITKIOMeta_LIBRARY_DIRS "")

