set(ITKIOTransformHDF5_LOADED 1)
set(ITKIOTransformHDF5_DEPENDS "ITKHDF5;ITKIOTransformBase")
set(ITKIOTransformHDF5_LIBRARIES "ITKIOTransformHDF5")
set(ITKIOTransformHDF5_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.4")
set(ITKIOTransformHDF5_LIBRARY_DIRS "")

