set(ITKIOBioRad_LOADED 1)
set(ITKIOBioRad_DEPENDS "ITKIOImageBase")
set(ITKIOBioRad_LIBRARIES "ITKIOBioRad")
set(ITKIOBioRad_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.4")
set(ITKIOBioRad_LIBRARY_DIRS "")

