set(ITKIOJPEG_LOADED 1)
set(ITKIOJPEG_DEPENDS "ITKIOImageBase;ITKJPEG")
set(ITKIOJPEG_LIBRARIES "ITKIOJPEG")
set(ITKIOJPEG_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.4")
set(ITKIOJPEG_LIBRARY_DIRS "")

