set(ITKIOGIPL_LOADED 1)
set(ITKIOGIPL_DEPENDS "ITKIOImageBase;ITKZLIB")
set(ITKIOGIPL_LIBRARIES "ITKIOGIPL")
set(ITKIOGIPL_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.4")
set(ITKIOGIPL_LIBRARY_DIRS "")

