set(ITKIOXML_LOADED 1)
set(ITKIOXML_DEPENDS "ITKExpat;ITKIOImageBase")
set(ITKIOXML_LIBRARIES "ITKIOXML")
set(ITKIOXML_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.4")
set(ITKIOXML_LIBRARY_DIRS "")

