set(ITKIORAW_LOADED 1)
set(ITKIORAW_DEPENDS "ITKIOImageBase")
set(ITKIORAW_LIBRARIES "ITKIOImageBase")
set(ITKIORAW_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.4")
set(ITKIORAW_LIBRARY_DIRS "")

