/* DO NOT EDIT.
 * Generated by ..\bin\Release\vtkEncodeString.exe
 * 
 * Declare the vtkGPUVolumeRayCastMapper_CompositeCroppingFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_CompositeCroppingFS_h
#define __vtkGPUVolumeRayCastMapper_CompositeCroppingFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_CompositeCroppingFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_CompositeCroppingFS_h */
