/* DO NOT EDIT.
 * Generated by ..\bin\Release\vtkEncodeString.exe
 * 
 * Declare the vtkGPUVolumeRayCastMapper_MIPFourDependentNoCroppingFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_MIPFourDependentNoCroppingFS_h
#define __vtkGPUVolumeRayCastMapper_MIPFourDependentNoCroppingFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_MIPFourDependentNoCroppingFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_MIPFourDependentNoCroppingFS_h */
