/* DO NOT EDIT.
 * Generated by ..\bin\Release\vtkEncodeString.exe
 * 
 * Declare the vtkGPUVolumeRayCastMapper_MinIPBinaryMaskFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_MinIPBinaryMaskFS_h
#define __vtkGPUVolumeRayCastMapper_MinIPBinaryMaskFS_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkGPUVolumeRayCastMapper_MinIPBinaryMaskFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_MinIPBinaryMaskFS_h */
