/* DO NOT EDIT.
 * Generated by ..\bin\Release\vtkEncodeString.exe
 * 
 * Declare the vtkGaussianBlurPassShader_fs string.
 *
 */
#ifndef __vtkGaussianBlurPassShader_fs_h
#define __vtkGaussianBlurPassShader_fs_h

#include "vtkSystemIncludes.h"

VTK_RENDERING_EXPORT extern const char *vtkGaussianBlurPassShader_fs;

#endif /* #ifndef __vtkGaussianBlurPassShader_fs_h */
