/* DO NOT EDIT.
 * Generated by ..\bin\Release\vtkEncodeString.exe
 * 
 * Declare the vtkVolumeTextureMapper3D_TwoDependentShadeFP string.
 *
 */
#ifndef __vtkVolumeTextureMapper3D_TwoDependentShadeFP_h
#define __vtkVolumeTextureMapper3D_TwoDependentShadeFP_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkVolumeTextureMapper3D_TwoDependentShadeFP;

#endif /* #ifndef __vtkVolumeTextureMapper3D_TwoDependentShadeFP_h */
